name: Demo

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v2.0.0
        with: 
          distribution: adopt
          java-version: 11

      - name: Build APK
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          gradle-version: current
          arguments: build
          
      - name: Create a Release
        uses: elgohr/Github-Release-Action@master
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      
      - name: Upload APK
        uses: actions/upload-artifact@v2.2.3
        with:
          name: Release
          path: app/build/outputs/apk/debug/app-debug.apk
            
