name: Demo

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: send message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#48f442"
          username: "GitHub Bot"
          message: "A new commit has been pushed with custom color."
      
      - name: Set up JDK
        uses: actions/setup-java@v2.0.0
        with: 
          distribution: adopt
          java-version: 11

      - name: Build APK
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          gradle-version: current
          arguments: build
      
      - name: Upload APK
        uses: ncipollo/release-action@v1.8.4
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          tag: Release
          artifacts: app/build/outputs/apk/debug/app-debug.apk
            
